### ISSUE TITLE
Cmake build issues

### ISSUE THREAD

**Issue by SpektacleFR** [Open-GD/OpenGD#50]
## Expected Output
Following build commands should work smoothly and compile/build the project without error.

## Real Output
When following directions listed in the README, I run the cmake command, as follows:
```
cmake -B build
```
and the build fails with this error:
```
CMake Error in /Users/$USER/Developer/opengd/axmol/core/CMakeLists.txt:
  The language OBJCXX was requested for compilation but was not enabled.  To
  enable a language it needs to be specified in a 'project' or
  'enable_language' command in the root CMakeLists.txt
```
As far as I can tell, Axmol is installed correctly (ran setup.py) and everything should work.  Maybe should I clone the OpenGD repo _inside_ the axmol folder?

## Device Specifications
MacBook Pro 16-inch (M2 Max) - macOS Ventura 13.4 (22F66)

**Comment by iAndyHD3** [comment]
OpenGD itself only builds on windows at the moment but this is an axmol issue. Not really sure since we don't use a mac. Maybe @halx99 can help

**Comment by halx99** [comment]
ONLY -GXcode supported.

**Comment by SergeyMC9730** [comment]
> OpenGD itself only builds on windows at the moment but this is an axmol issue. Not really sure since we don't use a mac. Maybe @halx99 can help
> 
> (use the [no header optimization branch](https://github.com/Open-GD/OpenGD/tree/no-header-optimization))

`no-header-optimization` works properly only on GCC, I couldn't get it to work on Clang. Please ensure that you would change default compiler.

**Comment by SergeyMC9730** [comment]
**UPD:** With commit ed299c8, OpenGD has been finally fixed on Linux.
