### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by XEN486** [Open-GD/OpenGD#57]
the gameplay feels off. that's my biggest complaint. I think it is because of the goofy camera. anyway here are the suggestions:

use both textures for the portal! I see only the foreground texture being used, it looks very wacky like this.

fix the bug where if you move the level select screen with your mouse, it desyncs. this just sucks

stop changing my icon for every level :P

**Comment by maxnut** [comment]
the project has been dead for like months

**Comment by XEN486** [comment]
bruhhhh
