### ISSUE TITLE
APK won't install 

### ISSUE THREAD

**Issue by KontrollFreek** [Open-GD/OpenGD#6]
Not sure if this is because I'm running Android 10 but the apk refuses to install immediately after trying
![Screenshot_20230319-101527.png](https://user-images.githubusercontent.com/72424960/226182106-6032c926-89ad-4585-ae45-3cdffbaba413.png)

**Comment by Kolyah35** [comment]
hmm maybe you have 32 bit architecture?

**Comment by zatrit** [comment]
Did you signed it?

**Comment by Kolyah35** [comment]
yes

**Comment by iAndyHD3** [comment]
this is simply that your device doesn't support armeabi x64, will be fixed in the next release
