### ISSUE TITLE
The level does not end

### ISSUE THREAD

**Issue by yahyagirayesen123** [Open-GD/OpenGD#60]
Hello. After playing the level, the level does not finish. I hope this will be resolved in the next update.

Take care of yourself

**Comment by Drtrayblox7855** [comment]
Hello, I'm gonna say it's pointless to post any issues here because the project is now unmaintained. You can look at the readme for projects that are similar to opengd.

**Comment by yahyagirayesen123** [comment]
Ok,Thank you
